### GET Request
GET https://jsonplaceholder.typicode.com/posts/1
Content-Type: application/json

### POST Request
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
  "title": "foo",
  "body": "bar",
  "userId": 1
}

###
curl --location 'https://playground.julius.ai/api/temp_user_id' \
--header 'Host: playground.julius.ai' \
--header 'sec-ch-ua: "Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"' \
--header 'use-dict: true' \
--header 'sec-ch-ua-mobile: ?1' \
--header 'user-agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Mobile Safari/537.362' \
--header 'cypress-test-id: None' \
--header 'gcs: true' \
--header 'interactive-charts: true' \
--header 'sec-ch-ua-platform: "Android"' \
--header 'accept: */*' \
--header 'origin: https://julius.ai' \
--header 'sec-fetch-site: same-site' \
--header 'sec-fetch-mode: cors' \
--header 'sec-fetch-dest: empty' \
--header 'referer: https://julius.ai/' \
--header 'accept-encoding: gzip, deflate, br, zstd' \
--header 'accept-language: en-US,en;q=0.9'









curl --location 'https://playground.julius.ai/api/chat/start' \
--header 'Host: playground.julius.ai' \
--header 'sec-ch-ua: "Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"' \
--header 'use-dict: true' \
--header 'pathname: /ai-chatbot' \
--header 'sec-ch-ua-mobile: ?1' \
--header 'authorization: Bearer' \
--header 'is-native: false' \
--header 'content-type: application/json' \
--header 'visitor-id: undefined' \
--header 'user-agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Mobile Safari/537.36' \
--header 'gcs: true' \
--header 'interactive-charts: true' \
--header 'request-id: undefined' \
--header 'is-demo: temp_2bb6cdd0-b8b3-455c-9b7b-a17ad38062dd' \
--header 'sec-ch-ua-platform: "Android"' \
--header 'accept: */*' \
--header 'origin: https://julius.ai' \
--header 'sec-fetch-site: same-site' \
--header 'sec-fetch-mode: cors' \
--header 'sec-fetch-dest: empty' \
--header 'referer: https://julius.ai/' \
--header 'accept-encoding: gzip, deflate, br, zstd' \
--header 'accept-language: en-US,en;q=0.9' \
--data '{
  "provider": "default",
  "server_type": "CPU",
  "template_id": null,
  "chat_type": null,
  "tool_preferences": null,
  "conversation_plan": null
}'






curl --location 'https://playground.julius.ai/api/chat/message' \
--header 'Host: playground.julius.ai' \
--header 'sec-ch-ua: "Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"' \
--header 'use-dict: true' \
--header 'pathname: /ai-chatbot' \
--header 'sec-ch-ua-mobile: ?1' \
--header 'authorization: Bearer' \
--header 'is-native: false' \
--header 'content-type: application/json' \
--header 'visitor-id: undefined' \
--header 'user-agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Mobile Safari/537.36' \
--header 'gcs: true' \
--header 'interactive-charts: true' \
--header 'request-id: undefined' \
--header 'is-demo: temp_2bb6cdd0-b8b3-455c-9b7b-a17ad38062dd' \
--header 'sec-ch-ua-platform: "Android"' \
--header 'accept: */*' \
--header 'origin: https://julius.ai' \
--header 'sec-fetch-site: same-site' \
--header 'sec-fetch-mode: cors' \
--header 'sec-fetch-dest: empty' \
--header 'referer: https://julius.ai/' \
--header 'accept-encoding: gzip, deflate, br, zstd' \
--header 'accept-language: en-US,en;q=0.9' \
--header 'conversation-id: 28b06b4c-a438-4230-b046-427bd340c724' \
--data '{
  "message": {
    "content": "siapa anda?"
  },
  "provider": "default",
  "chat_mode": "auto",
  "client_version": "20240130",
  "theme": "light",
  "new_images": null,
  "new_attachments": null,
  "dataframe_format": "json",
  "selectedModels": null
}'